name: Build Android
on:
  push:
    branches: [android]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.0'
      - name: Install Dependencies
        run: npm install
      
      - name: Install dependencies
        run: npm install
        
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: list files
        run: ls -lrt android/app/build/outputs/apk/release

#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: release
#           path: android/app/build/outputs/apk/release/app-release.apk

      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          token: ${{secrets.FIREBASE_TOKEN}}
          file: android/app/build/outputs/apk/release/app-release.apk
