name: iOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        
    - run: npm ci

    - run: xcode-select -p
    
    - run: pod install
      working-directory: ios
      name: Install pod dependencies

    - name: Build and archive
      run: |
        xcodebuild -workspace ios/AwesomeProject.xcworkspace -scheme iOS -archivePath $PWD/AwesomeProject archive
        xcodebuild -exportArchive -archivePath $PWD/AwesomeProject.xcarchive -exportPath . -exportOptionsPlist info.plist

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: Demo
        path: Demo.ipa

#     - name: Build iOS (debug)
#       run: "xcodebuild -workspace ios/AwesomeProject.xcworkspace -scheme iOS clean archive -sdk iphoneos -configuration Debug -UseModernBuildSystem=NO -archivePath $PWD/AwesomeProject CODE_SIGNING_ALLOWED=NO"

#     - name: Build ipa
#       run: |
#         xcodebuild -exportArchive -archivePath $PWD/AwesomeProject -exportPath $PWD . -exportOptionsPlist $PWD/AwesomeProject.xcarchive/info \

#     - name: Compress .xcarchive
#       run: zip -r -9 AwesomeProject.xcarchive.zip $PWD/AwesomeProject.xcarchive/

#     - uses: actions/upload-artifact@v2
#       with:
#         name: ios-xarchive
#         path: AwesomeProject.xcarchive.zip
        
