name: Build and Distribute iOS App

on:
  push:
    branches: [ios]

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

jobs:
  build-and-distribute:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: firebase login:ci --token "${{ env.FIREBASE_TOKEN }}"

      - name: Build iOS app
        run: |
          xcodebuild archive \
            -workspace YourProject.xcworkspace \
            -scheme YourProject \
            -configuration Release \
            -archivePath YourProject.xcarchive

      - name: Distribute app through Firebase
        run: |
          firebase appdistribution:distribute YourProject.xcarchive \
            --app YourFirebaseAppID \
            --release-notes "Your release notes"

      - name: Upload app to Apple Store
        uses: fastlane/fastlane@2.191.0
        with:
          subcommand: deliver
          ipa: YourProject.ipa
          username: ${{ env.FASTLANE_USER }}
          password: ${{ env.FASTLANE_PASSWORD }}
          skip_screenshots: true
